[workspace]
authors = ["HU Xuesong <87519979+huxs001@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda", "nvidia"]
name = "gpu4pyscf"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pyscf = ">=2.10.0,<3"
geometric = ">=1.1,<2"
pip = ">=25.2,<26"
libcutensor-cuda-12 = ">=2.3.1.0,<3"
basis_set_exchange = ">=0.11,<0.12"
nccl = ">=2.27.7.1,<3"
cuda-version = "12.*"

[pypi-dependencies]
nvidia-cuda-runtime-cu12 = ">=12.9.79, <13"
gpu4pyscf-cuda12x = ">=1.4.3, <2"

